### ISSUE TITLE
Saved credentials forgotten after update.

### ISSUE THREAD

**Issue by kruug** [HearthProject/OneClient#61]
Logged in at the client's main screen.  Checked "Save Credentials" box.  After update, had to re-login.

**Comment by modmuss50** [comment]
Is there anything in the log?

**Comment by kruug** [comment]
[16:00:44] [JavaFX Application Thread/ERROR]: An Error has occurred:
java.io.InvalidClassException: com.hearthproject.oneclient.util.minecraft.AuthStore; local class incompatible: stream classdesc serialVersionUID = 2781796664816095129, local class serialVersionUID = 2714229738697339757
	at java.io.ObjectStreamClass.initNonProxy(Unknown Source) ~[?:1.8.0_144]
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source) ~[?:1.8.0_144]
	at java.io.ObjectInputStream.readClassDesc(Unknown Source) ~[?:1.8.0_144]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[?:1.8.0_144]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:1.8.0_144]
	at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_144]
	at com.hearthproject.oneclient.fx.controllers.MinecraftAuthController.getAuthStore(MinecraftAuthController.java:185) ~[OneClient.jar:0.0.7.186]
	at com.hearthproject.oneclient.fx.controllers.MinecraftAuthController.load(MinecraftAuthController.java:51) ~[OneClient.jar:0.0.7.186]
	at com.hearthproject.oneclient.Main.startLauncher(Main.java:137) ~[OneClient.jar:0.0.7.186]
	at com.hearthproject.oneclient.Main.lambda$null$1(Main.java:81) ~[OneClient.jar:0.0.7.186]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:218) ~[jfxrt.jar:?]
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511) ~[jfxrt.jar:?]
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583) ~[jfxrt.jar:?]
	at javafx.stage.Stage.showAndWait(Stage.java:474) ~[jfxrt.jar:?]
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162) ~[jfxrt.jar:?]
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341) ~[jfxrt.jar:?]
	at com.hearthproject.oneclient.Main.lambda$startOneClient$0(Main.java:69) ~[OneClient.jar:0.0.7.186]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by modmuss50** [comment]
strange, can you trying deleting the authstore.dat file in your installation directory and then trying again?

**Comment by kruug** [comment]
After logging in again the credentials stay.

**Comment by modmuss50** [comment]
ok, so deleting that file fixed it? I should try and catch that error and delete the file

**Comment by kruug** [comment]
I didn't delete the file before logging in.
